name: neoflex_quiz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  audioplayers: ^6.4.0
  collection: ^1.19.0
  flutter:
    sdk: flutter
  flutter_animate: 4.2.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  lottie: ^3.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/images/
    - assets/svg/
    - assets/audio/
    - assets/animations/
